### ISSUE TITLE
Write /support

### ISSUE THREAD

**Issue by veganstraightedge** [allattacknoholdback/magazine#2]
We need funding from our readers. Here's why and how.

**Comment by veganstraightedge** [comment]
@morexfire

**Comment by morexfire** [comment]
Support

We navigate through a world of contradictions and the All Attack, No Hold Back project is no different. We adamantly oppose Capitalism, but find ourselves at it’s mercy, asking others for monetary support. After all, we still need to keep the wireless bill paid. We speak out against authority, skewer pop culture, and reject common ideas of property and progress, and yet, find it difficult to establish alternatives in meaningful, rewarding and sustainable ways. AANHB recognizes these inconsistencies and contradictions, then navigates through them as best we can, with the hope that our ultimate offering opens up the space in our discussions and lives to establish those necessary alternatives we seek through attacking dominant culture. 

With that said, there are lines to be drawn. In an attempt to reject the commodification of, well, everything, AANHB will never accept advertising money, and we’ll never build a paywall to keep borders around ideas. The push for a new existence will not be attained through secrets, whispers, and intellectual property, therefore, the ideas and expressions we offer will remain as accessible to you as they are to us. 

There is still, however, that wireless bill to be paid…not to mention the wireless bills of our authors. With that in mind, we are asking your financial support in hoping to keep the spirit of AANHB flourishing, allowing us the time and space to expand upon our ideas and expressions, to spread inflammatory rhetoric like wildfires, to reach deeper into that personal space that harbors our discontent and set it free. To be succinct, we need your help to attack. 

Our editorial organization is carving out the personal space to find time on the intellectual and emotional front lines of attack, and though we don’t all have this opportunity, financial contributions will help keep our collective ideas spreading, enable authors and editors to put in the necessary work that comprises radical social change, and keep that connection to the world strong. Don’t belabor your current predicament that may seem rife with more political contradictions than you care to admit, whether you are confined to looking at graphs and statistics on a computer screen all day or worn thin from the physically demanding work of repetitive labor, your contributions are crucial to keeping the radical fires burning bright. 

We humbly ask you to consider supporting our project, to play a fundamental role in keeping our ideas on the offensive, to help us initiate attacks where we can all take part directly. 

“The freest individual is the one with nothing left to lose.”
